[project]
name = "1-basic-rest-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.5.3",
    "fastapi[standard]>=0.117.1",
    "redis>=6.4.0",
    "uvicorn>=0.37.0",
]
